### ISSUE TITLE
Initialising USB HDD causes error

### ISSUE THREAD

**Issue by WizHQ** [beyonwiz-dev/enigma2#1]
Image 6.3 2019-03-03
Connect external HDD via USB and try to initialise via setup menu and you get onscreen error:
Error: unmount: can't unmount /media/hdd: Device or resource busy

*log attached 
[Enigma2-debug-20190305_23-29-37.log](https://github.com/beyonwiz-dev/enigma2/files/2930906/Enigma2-debug-20190305_23-29-37.log)

**Comment by atvcaptain** [comment]
fixed: https://github.com/oe-alliance/oe-alliance-core/commit/06826e2b5a5905a65bf5281bb862d3749a326caf

include in 2019-03-06
