### ISSUE TITLE
Some Automatic Resolution settings unable to use 2160p

### ISSUE THREAD

**Issue by MrQuade** [beyonwiz-dev/enigma2#11]
If the Automatic Resolution option is set to "All resolutions" or "only HD", then 2160p is not a selectable output resolution for any source material.

**Comment by MrQuade** [comment]
Also of note is that when the "Simple" Autoresolution option is enabled, the resolution is unnecessarily changed when switching between media with the same video output settings.

For example.
If Live TV is running in the background at 1080i50, and is being output at 2160p50, then a 576i50 recording is played back, the TV blanks out for a moment as if the resolution is being changed, but the resulting resolution is still 2160p50.

If the correct resolution is already set, then the Autoresolution feature should not attempt to "change" the resolution.

**Comment by atvcaptain** [comment]
update with drivers 2019.03.20 please check

**Comment by MrQuade** [comment]
2160p video moded are still missing when Automatic Resolution is set to "All resolutions" and "only HD".

2160p is still available in "Simple" and "Native" mode.

**Comment by atvcaptain** [comment]
now include the modes
