### ISSUE TITLE
V2 Unable to downmix or pass-through Dolby True-HD

### ISSUE THREAD

**Issue by MrQuade** [beyonwiz-dev/enigma2#13]
The V2 can successfully both downmix and pass-through DD, DD+, DTS, and DTS-MA soundtracks, but is unable to properly deal with DH True-HD, and DD True-HD w. ATMOS.

When these True-HD soundtracks are played, only a stereo PCM signal is received by the audio equipment.  The stereo signal only seems to include 2 channels worth of audio, so the audio from the remaining 5.1 channels is completely absent.

Sample files can be found here:
https://thedigitaltheater.com/dolby-trailers/

**Comment by atvcaptain** [comment]
hw limit not supoortet drivers downmix to stereo better as no sound
