### ISSUE TITLE
EPG rendering flickers during navigation

### ISSUE THREAD

**Issue by MrQuade** [beyonwiz-dev/enigma2#16]
The Graphical EPG and Infobar EPG will flicker briefly when the user navigates between events.
This is apparent in both text and graphics modes.

Flickering is also apparent in setup screens when options are toggled.

**Comment by atvcaptain** [comment]
driver issue with accel

**Comment by MrQuade** [comment]
This appears to be resolved in the 27032019 firmware image.

**Comment by MrQuade** [comment]
Latest drivers in today's update appear to have resolved this.
