### ISSUE TITLE
Front panel can not display some characters

### ISSUE THREAD

**Issue by peterurbanec** [beyonwiz-dev/enigma2#19]
The front panel 7-segment LED display can not display many ASCII characters. The following characters result in blanks:

```fgjklmpqsvwxyzBDJKMQTVWXYZ.,*@#$%^&?/;(){}[]|!~`+=_```

This causes the unit to look like it has hardware failure issues when used with a skin that writes to front panel. It is understandable that some of the above characters can not be displayed. However, it should be possible to display a few more. For example ```f``` could be displayed same as ```F``` and it should be possible to come up with a set of segments to resemble ```y``` and ```Y```.

**Comment by peterurbanec** [comment]
This is relatively low priority. Even with more characters supported, a 4 digit, 7 segment LED front panel is still not suitable to display sophisticated messages.

**Comment by atvcaptain** [comment]
update with drivers 2019.03.20 please check

**Comment by peterurbanec** [comment]
Issue mitigated with front panel skin.
