### ISSUE TITLE
Messages log spammed if V2 is running with no display attached

### ISSUE THREAD

**Issue by MrQuade** [beyonwiz-dev/enigma2#8]
If the V2 is started up and the TV and/or receiver is not switched on or responding to HDMI-CEC commands, the /var/log/messages log is filled up with constant messages:

eg.
Mar 10 21:52:56 beyonwizv2 user.warn kernel: poll CEC 0 NOT VALID!

**Comment by atvcaptain** [comment]
fixed with update with drivers 2019.03.20 please check
